version: '3'

services:
  flask-app:
    image: flask-notes-app:latest
    ports:
      - "80:80"
    networks:
      - notes
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespassword
    networks:
      - notes

networks:
  notes:
